Milestone 5
Deepakdanger/bookstore_library pull request #5
Opened 2021-10-23 10:13 UTC by Deepakdanger

Here, In this milestone, Styling is done according to zeplin bookstore websites.
- Done styling of navbar.
- Done styling on books specification.
- Done styling on forms

2021-10-23 11:23 UTC, addod19 requested changes
### Hi @Deepakdanger, 

Good job so far! Great job implementing the placeholders :fireworks: Git-flow followed :100: 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Capitalizing all our commit messages, to make the PR consistent and professional

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-23 11:23 UTC, addod19 commented on src/App.css
> +  letter-spacing: normal;
- [x] It would be better if we implement the CSS DRY principle, these rules have been repeated. Let us kindly fix them. We can fix this by giving these rules a common class like `.common { ....... }`

2021-10-23 11:23 UTC, addod19 commented on src/App.css
> +
- [x] It would be better if our design or styling is exactly as the given design. Let us kindly compare our design to the given design
![Screenshot from 2021-10-23 11-14-32](https://user-images.githubusercontent.com/46388113/138553751-2211b7c9-66fb-40e7-9b19-e3563f8b8a62.png)
here is our design below
![Screenshot from 2021-10-23 11-17-33](https://user-images.githubusercontent.com/46388113/138553847-a89c2268-a9f0-4854-8f3d-bf5378c37905.png)
Let us consider the border, background-color, color, text, alignment of the header to the book list, etc

Here is the add book UI input
![Screenshot from 2021-10-23 11-19-54](https://user-images.githubusercontent.com/46388113/138553906-57be7dd8-e76b-4119-afac-58b0135dd97f.png)

2021-10-24 12:42 UTC, rukundoeric approved these changes
Hi @Deepakdanger,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-24 15:25 UTC, merged